apiVersion: v1
kind: Pod
metadata:
  name: busybox-peacefulwhale
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "-m"
      - "5"
    resources:
      requests:
        cpu: 0.125
        memory: 500Mi
      limits:
        cup: 0.125
        memory: 600Mi
    imagePullPolicy: IfNotPresent
    name: busybox-peacefulwhale
  restartPolicy: Always