apiVersion: v1
kind: Pod
metadata:
  name: peacefulwhale
  namespace: default
spec:
  containers:
  - image: unpeacefulwhale/cit-270-pw
    volumeMounts:
    - name: ssl
      mountPath: "/usr/src/app/SSL"
    command: ["/bin/bash"]
    args: ["./start.sh"]
    resources:
      requests:
        cpu: 0.125
        memory: 500Mi
      limits:
        cpu: 0.125
        memory: 600Mi
    imagePullPolicy: IfNotPresent
    name: peacefulwhale
  volumes:
  - name: ssl
    secret: 
      secretName: ssl.secret
  restartPolicy: Always
