apiVersion: apps/v1
metadata:
  name: pw-deployment
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peacefulwhale
  template:
    metadata:
      labels:
        app: peacefulwhale
    spec:
      containers:
      - name: pw-cit-270
        image: unpeacefulwhale/cit-270-pw:latest
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["/bin/bash"]
        args: ["./start.sh"]
        ports:
          - containerPort: 443
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: IfNotPresent
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pw-loadbalancer
spec:
  selector:
    app: peacefulwhale
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
